name: pull-request-workflow 1
on: 
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-18.04.6
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action