name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - name: github context
      run: echo '${{ toJson(github) }}'
    - name: check github context
      run: |
        echo github_repository: ${{ github.repository }}
        echo github_event_name: ${{ github.event_name }}